import type { DocumentTypeConfig } from "@/types";

export const DOCUMENT_CONFIGS: DocumentTypeConfig[] = [
  {
    id: "estimate",
    label: "見積書",
    description: "プロジェクトの費用見積もりを作成",
    icon: "📋",
    fields: [
      { key: "clientName", label: "クライアント名", type: "text", placeholder: "株式会社〇〇 御中", required: true },
      { key: "projectName", label: "案件名", type: "text", placeholder: "Webサイトリニューアル", required: true },
      { key: "projectDescription", label: "作業内容", type: "textarea", placeholder: "Webサイトのデザイン・コーディング・CMS実装...", required: true },
      { key: "amount", label: "見積金額（円）", type: "number", placeholder: "500000", required: true },
      { key: "deliveryDate", label: "納期", type: "date", required: true },
      { key: "validityPeriod", label: "見積有効期限（日数）", type: "number", placeholder: "30", required: false },
      { key: "yourName", label: "自分の名前・屋号", type: "text", placeholder: "山田太郎 / やまだデザイン事務所", required: true },
      { key: "notes", label: "備考・特記事項", type: "textarea", placeholder: "修正回数3回まで含む。追加修正は別途見積。", required: false },
    ],
  },
  {
    id: "invoice",
    label: "請求書",
    description: "納品後の請求書を即座に生成",
    icon: "💰",
    fields: [
      { key: "clientName", label: "クライアント名", type: "text", placeholder: "株式会社〇〇 御中", required: true },
      { key: "projectName", label: "案件名", type: "text", placeholder: "Webサイトリニューアル", required: true },
      { key: "projectDescription", label: "作業内容", type: "textarea", placeholder: "Webサイトのデザイン・コーディング・CMS実装", required: true },
      { key: "amount", label: "請求金額（円・税抜）", type: "number", placeholder: "500000", required: true },
      { key: "taxRate", label: "消費税率", type: "select", options: ["10%", "8%", "0%"], required: true },
      { key: "invoiceDate", label: "請求日", type: "date", required: true },
      { key: "paymentDueDate", label: "支払期限", type: "date", required: true },
      { key: "bankInfo", label: "振込先口座情報", type: "textarea", placeholder: "〇〇銀行 〇〇支店 普通 1234567 ヤマダ タロウ", required: true },
      { key: "yourName", label: "自分の名前・屋号", type: "text", placeholder: "山田太郎 / やまだデザイン事務所", required: true },
    ],
  },
  {
    id: "contract",
    label: "業務委託契約書",
    description: "法的に有効な契約書を自動生成",
    icon: "📄",
    fields: [
      { key: "clientName", label: "委託者（クライアント）名", type: "text", placeholder: "株式会社〇〇", required: true },
      { key: "clientAddress", label: "委託者の住所", type: "text", placeholder: "東京都渋谷区〇〇1-2-3", required: true },
      { key: "yourName", label: "受託者（自分）名", type: "text", placeholder: "山田太郎", required: true },
      { key: "yourAddress", label: "受託者の住所", type: "text", placeholder: "東京都新宿区〇〇4-5-6", required: true },
      { key: "projectName", label: "業務内容", type: "text", placeholder: "Webサイトリニューアル業務", required: true },
      { key: "projectDescription", label: "業務詳細", type: "textarea", placeholder: "WebサイトのUI/UXデザイン、フロントエンド実装、CMS導入...", required: true },
      { key: "amount", label: "報酬金額（円・税抜）", type: "number", placeholder: "500000", required: true },
      { key: "startDate", label: "業務開始日", type: "date", required: true },
      { key: "endDate", label: "業務終了日（納期）", type: "date", required: true },
      { key: "paymentTerms", label: "支払条件", type: "textarea", placeholder: "納品後30日以内に指定口座へ振込", required: true },
      { key: "specialClauses", label: "特別条項（任意）", type: "textarea", placeholder: "秘密保持義務、著作権の帰属など", required: false },
    ],
  },
  {
    id: "proposal",
    label: "提案書",
    description: "クライアントを説得する提案書を作成",
    icon: "✨",
    fields: [
      { key: "clientName", label: "クライアント名", type: "text", placeholder: "株式会社〇〇", required: true },
      { key: "clientIndustry", label: "クライアントの業種・課題", type: "textarea", placeholder: "ECサイト運営。売上が伸び悩んでいる。", required: true },
      { key: "projectName", label: "提案タイトル", type: "text", placeholder: "売上120%アップのWebサイトリニューアル提案", required: true },
      { key: "solution", label: "提案内容・解決策", type: "textarea", placeholder: "UX改善とCVR最適化により、コンバージョン率を現在の1.2%から2.5%に改善...", required: true },
      { key: "yourStrength", label: "自分の強み・実績", type: "textarea", placeholder: "EC系の改善実績10社以上。平均CVR向上率150%。", required: true },
      { key: "amount", label: "提案金額（円）", type: "number", placeholder: "500000", required: true },
      { key: "timeline", label: "スケジュール", type: "textarea", placeholder: "Week1: 要件定義 / Week2-3: デザイン / Week4-5: 実装 / Week6: テスト・納品", required: true },
      { key: "yourName", label: "自分の名前・屋号", type: "text", placeholder: "山田太郎 / やまだデザイン事務所", required: true },
    ],
  },
];
